### ISSUE TITLE
Analog reads is returning values 0-65535 instead of 0-1023

### ISSUE THREAD

**Issue by jpagliaccio** [n-wach/camino#10]
Analog reads is returning values 0-65535 (in increments of 257?) when it should be returning 0-1023.
Can you take a look? I can test?

```
void _analogRead(byte dataLength, byte *dataArray) {
  int value = analogRead(dataArray[0]);
  byte arr[2] = {(byte) (value % 256), (byte) value};
  returns(2, arr);
}

```
Thanks

**Comment by n-wach** [comment]
Oops, yeah I think the second entry in `arr` should be `value / 256`.

Let me know if that fixes it and I'll push an update.

**Comment by jpagliaccio** [comment]
That's not working. 

`  byte arr[2] = {(byte) (value % 256), (byte) value/256};
`
Puts it back to 0-255.  
Don't we need to split into dataArray[0] and dataArray[1]? Eg, it's 0-1024.   

A hack would be something like this, but you did such a nice job of the code it would be nice to have it correct. 

```
void _analogRead(byte dataLength, byte *dataArray) {
  int value = analogRead(dataArray[0]);
  byte arr[2] = {(byte) (value % 256), (byte) value/64};
  returns(2, arr);
}

```

**Comment by n-wach** [comment]
Can you try with parenthesis, like:

```
byte arr[2] = { (byte) (value % 256), (byte) (value / 256) };
```

Without them, the cast is happening first, which makes it always 0 after the division. 

We want to send the value in little endian, which means the least significant byte goes first (we get with %256), then the second byte (we get with /256). This works because our value is within the range of 2 bytes.

**Comment by jpagliaccio** [comment]
Great - that's working now. 
Thanks for the explanation. 

Here is the whole working function: 

It returns 0-1023 for 0V - 5V (on a Mega).  

```
void _analogRead(byte dataLength, byte *dataArray) {
  int value = analogRead(dataArray[0]);
  byte arr[2] = { (byte) (value % 256), (byte) (value / 256) };
  returns(2, arr);
}

```

**Comment by n-wach** [comment]
Great, thanks for verifying. I’ve generalized what we’re doing here to support returning byte, short, int, long directly. So this turns into just `returns((short) value)`.

Going to release a new version. Would be great if you could test once it’s out. 

Thanks again for your help with this!

**Comment by n-wach** [comment]
Pushed. Let me know if everything is still working. If you could also test a callable that uses `returns((int) some_big_int)`, that would be great :)

**Comment by jpagliaccio** [comment]
So `returns((int) some_big_int)` returns from 0-255 and then resets to 0. 
255 is the maximum it returns right now.

**Comment by n-wach** [comment]
Huh, that's strange. Is `_analogRead` working correctly?

**Comment by jpagliaccio** [comment]
I had not downloaded a new version of Camino.cc. I was using my copy. Sorry didn't know you made other changes. So now with your latest version downloaded from the library manager we get this.  

`returns((long)x); ` works up to 2147483648 then the values are not correct (see below). 

Using this code to test and calling it in a python loop: 

```
// unsigned long x = 2147483647L;  // max for 32 bit int 
// same results for long and unsigned long - casted to long on return 
long x = 2147483640L; 

void returnLong() { 
  x = x + 1L; 
  returns((long)x);
}
```

longInt = 2147483641 
longInt = 2147483642 
longInt = 2147483643 
longInt = 2147483644 
longInt = 2147483645 
longInt = 2147483646 
longInt = 2147483647 
longInt = **2147483648** --- good to here 
longInt = 2164326657 
longInt = 2164326658 
longInt = 2164326659 
longInt = 2164326660 
longInt = 2164326661 
longInt = 2164326662 
longInt = 2164326663 
longInt = 2164326664 
longInt = 2164326665 
longInt = 2164326666

**Comment by n-wach** [comment]
I forgot that types on Arduino were smaller than usual. So I actually think this is what we expect. Here’s a table with the sizes of various types on Arduino: https://robotresearchlab.com/2016/11/14/variable-data-types/


I think there’s just some weird overflow happening because `long` is 4 bytes. I’m going to add `returns` for the unsigned types. And I will add a `signed` option to the Python callable.

**Comment by n-wach** [comment]
I got my hands on an Arduino. Made some changes, wrote some tests, and everything looks good now. 

Thanks again for your help! Let me know if you find anything else
