### ISSUE TITLE
Analog write value 

### ISSUE THREAD

**Issue by jpagliaccio** [n-wach/camino#13]
Hey Nathan,

Starting line 393 in Camino.cpp, analog write only accepts a value between 0-254. Shouldn't the write value be dataArray[1]. It seems to work when I test. 

Analog read is 10 bit, 0-1023
Analog write is 0-255

```
void _analogWrite(byte dataLength, byte *dataArray) {
  // analogWrite(dataArray[0], dataArray[1]*256 + dataArray[2]); // was this 
  analogWrite(dataArray[0], dataArray[1]);  // Should be this? 
}

```
Thanks

**Comment by n-wach** [comment]
Yep, you’re right. 

Any chance you could make a Pull Request with this fix? No worries if not, but a PR would at least add your name under the contributors tab.

**Comment by jpagliaccio** [comment]
I gave it a try :)
