### ISSUE TITLE
`set_input_flow_control` pyserial method is only available on POSIX systems. 

### ISSUE THREAD

**Issue by NotNotQuinn** [n-wach/camino#4]
When using `camino` from windows, the `Serial.set_input_flow_control` method doesn't exist. This means windows users cannot use the package as is.

Although I dont think any of these are used, other platform-specific methods to watch out for are:
* `nonblocking()`
* `fileno()`
* `set_output_flow_control()`
* `cancel_read()`
* `cancel_write()`

[docs](https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.set_input_flow_control) ([archive.org](https://web.archive.org/web/20221127011711/https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.set_input_flow_control))

**Comment by n-wach** [comment]
Thanks for the heads up! I just tested, and `camino` seems to work fine (on linux) after removing the `Serial.set_input_flow_control` call. I will remove the call and push an update.

**Comment by n-wach** [comment]
Just confirmed, version `1.2.0` of `camino` is now working on Windows. Thanks again!

**Comment by NotNotQuinn** [comment]
Thanks for the speedy update!
